routes/frontend.php
<?php

use App\Http\Controllers\Frontend\BookController;
use App\Http\Controllers\Frontend\PostAdvertisementController;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('frontend.home');
Route::get('/contact', 'ContactController@contact')->name('frontend.contact');
Route::post('/contact/store', 'ContactController@store')->name('frontend.contact.store');

Route::get('/post-ad', [PostAdvertisementController::class, 'index'])->name('frontend.post_ad');
Route::post('/post-ad/book/store', [PostAdvertisementController::class, 'store'])->name('frontend.post_ad.store');
Route::get('/post-ad/book/{book}/edit', [PostAdvertisementController::class, 'edit'])->name('frontend.post_ad.edit');
Route::patch('/post-ad/book/{book}/update', [PostAdvertisementController::class, 'update'])->name('frontend.post_ad.update');
Route::get('/book/sold/{id}', [PostAdvertisementController::class, 'soldBook'])->name('frontend.book.sold');
Route::delete('/book/{book}/delete', [PostAdvertisementController::class, 'destroy'])->name('frontend.book.delete');
Route::get('/getSubCategories/{id}', [\App\Http\Controllers\Backend\TernaryCategoryController::class, 'getSubCategories']);
Route::get('/getTernaryCategories/{id}', [\App\Http\Controllers\Backend\BookController::class, 'getTernaryCategories']);
Route::get('/books/list', [BookController::class, 'bookList'])->name('frontend.book.list');
Route::get('/books/category/{category}/list', [BookController::class, 'categoryList'])->name('frontend.book.category.list');
Route::get('/book/{id}/detail', [BookController::class, 'bookDetail'])->name('frontend.book.detail');
Route::get('/books/sub-category/{sub_category}/list', [BookController::class, 'subCategoryList'])->name('frontend.book.subcategory.list');
Route::get('/books/ternary-category/{ternary_category}/list', [BookController::class, 'ternaryCategoryList'])->name('frontend.book.ternary_category.list');
Route::get('/books/search', [BookController::class, 'search'])->name('frontend.book.search');
Route::post('projects/media', [\App\Http\Controllers\Backend\BookController::class, 'storeMedia'])->name('books.storeMedia');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'App\Http\Controllers\Backend', 'middleware' => 'auth'],function(){
    /* Dashboard */
//    Route::get('/', function () {
//        return view('backend.dashboard');
//    });
    Route::get('dashboard', function () {
        return view('backend.dashboard');
    })->name('dashboard');
    Route::get('profile', function () {
        return view('auth.profile');
    })->name('admin.profile');
    Route::post('update-profile','UserController@updateProfile')->name('auth.update-profile');
    Route::post('change-password', 'UserController@changePassword')->name('auth.change-password');


    Route::resource('site-setting', 'SiteSettingController');
    Route::resource('category', 'CategoryController');
    Route::resource('sub_category', 'SubCategoryController');
    Route::resource('ternary_category', 'TernaryCategoryController');
    Route::resource('book', 'BookController');
    Route::resource('contact', 'ContactController');
    Route::get('/getSubCategories/{id}', [\App\Http\Controllers\Backend\TernaryCategoryController::class, 'getSubCategories']);
    Route::get('/getTernaryCategories/{id}', [\App\Http\Controllers\Backend\BookController::class, 'getTernaryCategories']);
    Route::post('projects/media', [\App\Http\Controllers\Backend\BookController::class, 'storeMedia'])->name('books.storeMedia');

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Book extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;
    protected $fillable = ['category_id', 'sub_category_id', 'ternary_category_id', 'customer_id','ad_type', 'title', 'price_type', 'price', 'item_condition', 'book_edition', 'description', 'status', 'is_featured'];
    protected $appends = ['images'];

   public function getImagesAttribute(){
       return $this->hasMedia('images') ? $this->getMedia('images') :'Images' ;
   }
    public function category(){
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
    public function sub_category(){
        return $this->belongsTo(SubCategory::class, 'sub_category_id', 'id');
    }
    public function ternary_category(){
        return $this->belongsTo(TernaryCategory::class, 'ternary_category_id', 'id');
    }
    public function customer(){
        return $this->belongsTo(Customer::class, 'customer_id', 'id');
    }
    public function scopeIsSold($query){
        return $query->where('status', 1);
    }
    public function scopeIsNotSold($query){
        return $query->where('status', 0);
    }
}

app/Http/Controllers/Backend/BookController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\BookRequest;
use App\Models\Book;
use App\Models\Category;
use App\Models\SubCategory;
use App\Models\TernaryCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('media')->latest()->orderBy('is_featured', 'desc')->get();
        return view('backend.book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::isActive()->latest()->get();
        $subCategories = SubCategory::isActive()->latest()->get();
        $ternaryCategories = TernaryCategory::isActive()->latest()->get();
        return view('backend.book.create', compact('categories', 'subCategories', 'ternaryCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookRequest $request)
    {
        $request['customer_id'] = Auth::guard('customer')->user()->id ?? Auth::user()->id;
        $book = Book::create($request->all());
        foreach ($request->input('images', []) as $file) {
            $book->addMedia(storage_path('frontend/img/book/' . $file))->toMediaCollection('images');
        }
        return redirect()->route('book.index')->withMsg('Book Created Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $categories = Category::isActive()->latest()->get();
        $subCategories = SubCategory::isActive()->latest()->get();
        $ternaryCategories = TernaryCategory::isActive()->latest()->get();
        return view('backend.book.create', compact('book', 'categories', 'subCategories', 'ternaryCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BookRequest $request, Book $book)
    {
        $request['customer_id'] = Auth::guard('customer')->user()->id ?? Auth::user()->id;
        $book->update($request->all());
    if  (count($book->images) > 0) {
        foreach ($book->images as $media) {
            if (!in_array($media->file_name, $request->input('images', []))) {
                $media->delete();
            }
        }
    }
    $media = $book->images->pluck('file_name')->toArray();

    foreach ($request->input('images', []) as $file) {
        if (count($media) === 0 || !in_array($file, $media)) {
            $book->addMedia(storage_path('frontend/img/book/' . $file))->toMediaCollection('images');
        }
    }

        return redirect()->route('book.index')->withMsg('Book Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        if ($book->hasMedia('images')){
            $book->clearMediaCollection('images');
        }
        $book->delete();
        return redirect()->route('book.index')->withMsg('Book deleted sucessfully');
    }

    public function getTernaryCategories($id){
        $subCategories = TernaryCategory::where('sub_category_id', $id)->get();
        return response(json_encode($subCategories));
    }
    public function storeMedia(Request $request)
    {
    $path = storage_path('frontend/img/book');

    if (!file_exists($path)) {
        mkdir($path, 0777, true);
    }

    $file = $request->file('file');

    $name = uniqid() . '_' . trim($file->getClientOriginalName());

    $file->move($path, $name);

    return response()->json([
        'name'          => $name,
        'original_name' => $file->getClientOriginalName(),
    ]);
}
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::latest()->orderBy('order', 'asc')->get();
        return view('backend.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('category.index')->withMsg('Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('backend.category.create', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('category.index')->withMsg('Category updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index')->withMsg('Category deleted successfully.');
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Contact;

class ContactController extends Controller
{
    public function index(){
        $contacts=Contact::latest()->get();
        return view('backend.contact', compact('contacts'));
    }
   public function destroy(Contact $contact){
        $contact->delete();
        return redirect()->route('contact.index')->withMsg('Message sucessfully deleted');
   }
}

app/Http/Controllers/Backend/SiteSettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\SiteSettingRequest;
use App\Models\SiteSetting;
use Illuminate\Http\Request;

class SiteSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = SiteSetting::first();
        return view('backend.settings.site', compact('edit'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SiteSettingRequest $request)
    {
        $edit = SiteSetting::first();
        if ($request->hasFile('logo')){
            $edit->clearMediaCollection();
            $edit->addMedia($request->file('logo'))->toMediaCollection();
        }
        if ($edit){
            $edit->update($request->all());
        }else{
           SiteSetting::create($request->all());
        }
        return redirect()->route('site-setting.index')->withMsg('Site Setting has been updated successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/SubCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Backend\SubCategoryRequest;
use App\Models\Category;
use App\Models\SubCategory;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subCategories = SubCategory::latest()->get();
        return view('backend.sub_category.index', compact('subCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::isActive()->get();
        return view('backend.sub_category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubCategoryRequest $request)
    {
        SubCategory::create($request->all());
        return redirect()->route('sub_category.index')->withMsg('Sub-Category Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(SubCategory $subCategory)
    {
        $categories = Category::isActive()->get();
        return view('backend.sub_category.create',compact('categories', 'subCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SubCategoryRequest $request, SubCategory $subCategory)
    {
        $subCategory->update($request->all());
        return redirect()->route('sub_category.index')->withMsg('Sub-Category Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(SubCategory $subCategory)
    {
        $subCategory->delete();
        return redirect()->route('sub_category.index')->withMsg('Sub-Category Deleted Successfully.');
    }
}

resources/views/backend/book/index.blade.php
@extends('backend.layouts.app')
@section('content')
    <?php
    use Carbon\Carbon;
    ?>
    <!-- Page Header -->
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <!-- <span class="text-uppercase page-subtitle">Overview</span> -->
            <h3 class="page-title">Book list</h3>
            <a href="{{route('book.create')}}" class="btn btn-primary mt-4 ml-2"><i class="fa fa-plus"></i> Add New Book</a>
        </div>
    </div>

    <!-- End Page Header -->
    <!-- Default Light Table -->
    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-body p-3 text-center">
                    <div class="table-responsive p-1">
                        <table id="event-table" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Images</th>
                                <th>Category Name</th>
                                <th>Sub-Category Name</th>
                                <th>Ternary Category Name</th>
                                <th>Title</th>
                                <th>Price</th>
                                <th>Status</th>
                                <th>Is Featured</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($books as $book)

                                <tr>
                                    <td class="font-weight-bold">{{ Carbon::parse($book->created_at)->format('Y M d H:i A')}}</td>
                                    <td>
                                        @foreach($book->media as $image)
                                        <img src="{{$image->getFullUrl()}}" alt="" height="100px"; width="100px">
                                        @endforeach
                                    </td>
                                    <td>{{$book->category->name}}</td>
                                    <th>{{$book->sub_category->name}}</th>
                                    <th>{{$book->ternary_category->name ?? "N/A"}}</th>
                                    <th>{{$book->title}}</th>
                                    <th>{{$book->price}}</th>
                                    <td class="text-center">
                                        @if($book->status==1)
                                            <span class="shadow-none badge badge-danger">Sold</span>
                                        @else
                                            <span class="shadow-none badge badge-success">Active</span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @if($book->is_featured==1)
                                            <span class="shadow-none badge badge-success">Featured</span>
                                        @else
                                            <span class="shadow-none badge badge-danger">Not Featured</span>
                                        @endif
                                    </td>
                                    <td>
                                        <div class="d-flex justify-content-center">
                                            <a class="btn btn-warning btn-sm mr-2" href="{{route('book.edit',$book)}}">Edit</a>
                                            <form action="{{route('book.destroy',$book)}}" method="post" onsubmit="return confirm('Are you sure?')">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-sm btn-danger mr-2"><i class="fa fa-trash text-white" title="Delete"></i> </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Default Light Table -->
    <script type="text/javascript">
        $(document).ready(function() {
            setTimeout(function() {
                $('.alert .close').click()
            }, 3000);
            $('#event-table').DataTable({
                "columnDefs": [{
                    "width": "100px",
                    "targets": 0
                },
                    {
                        "width": "150px",
                        "targets": 1
                    },
                    {
                        "width": "150px",
                        "targets": 2
                    },
                    {
                        "width": "70px",
                        "targets": 3
                    },
                ],
            });
        });
    </script>
@endsection