routes/frontend.php
<?php

use App\Http\Controllers\Frontend\BookController;
use App\Http\Controllers\Frontend\PostAdvertisementController;
use Illuminate\Support\Facades\Route;

Route::get('/', 'HomeController@index')->name('frontend.home');
Route::get('/contact', 'ContactController@contact')->name('frontend.contact');
Route::post('/contact/store', 'ContactController@store')->name('frontend.contact.store');

Route::get('/post-ad', [PostAdvertisementController::class, 'index'])->name('frontend.post_ad');
Route::post('/post-ad/book/store', [PostAdvertisementController::class, 'store'])->name('frontend.post_ad.store');
Route::get('/post-ad/book/{book}/edit', [PostAdvertisementController::class, 'edit'])->name('frontend.post_ad.edit');
Route::patch('/post-ad/book/{book}/update', [PostAdvertisementController::class, 'update'])->name('frontend.post_ad.update');
Route::get('/book/sold/{id}', [PostAdvertisementController::class, 'soldBook'])->name('frontend.book.sold');
Route::delete('/book/{book}/delete', [PostAdvertisementController::class, 'destroy'])->name('frontend.book.delete');
Route::get('/getSubCategories/{id}', [\App\Http\Controllers\Backend\TernaryCategoryController::class, 'getSubCategories']);
Route::get('/getTernaryCategories/{id}', [\App\Http\Controllers\Backend\BookController::class, 'getTernaryCategories']);
Route::get('/books/list', [BookController::class, 'bookList'])->name('frontend.book.list');
Route::get('/books/category/{category}/list', [BookController::class, 'categoryList'])->name('frontend.book.category.list');
Route::get('/book/{id}/detail', [BookController::class, 'bookDetail'])->name('frontend.book.detail');
Route::get('/books/sub-category/{sub_category}/list', [BookController::class, 'subCategoryList'])->name('frontend.book.subcategory.list');
Route::get('/books/ternary-category/{ternary_category}/list', [BookController::class, 'ternaryCategoryList'])->name('frontend.book.ternary_category.list');
Route::get('/books/search', [BookController::class, 'search'])->name('frontend.book.search');
Route::post('projects/media', [\App\Http\Controllers\Backend\BookController::class, 'storeMedia'])->name('books.storeMedia');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'App\Http\Controllers\Backend', 'middleware' => 'auth'],function(){
    /* Dashboard */
//    Route::get('/', function () {
//        return view('backend.dashboard');
//    });
    Route::get('dashboard', function () {
        return view('backend.dashboard');
    })->name('dashboard');
    Route::get('profile', function () {
        return view('auth.profile');
    })->name('admin.profile');
    Route::post('update-profile','UserController@updateProfile')->name('auth.update-profile');
    Route::post('change-password', 'UserController@changePassword')->name('auth.change-password');


    Route::resource('site-setting', 'SiteSettingController');
    Route::resource('category', 'CategoryController');
    Route::resource('sub_category', 'SubCategoryController');
    Route::resource('ternary_category', 'TernaryCategoryController');
    Route::resource('book', 'BookController');
    Route::resource('contact', 'ContactController');
    Route::get('/getSubCategories/{id}', [\App\Http\Controllers\Backend\TernaryCategoryController::class, 'getSubCategories']);
    Route::get('/getTernaryCategories/{id}', [\App\Http\Controllers\Backend\BookController::class, 'getTernaryCategories']);
    Route::post('projects/media', [\App\Http\Controllers\Backend\BookController::class, 'storeMedia'])->name('books.storeMedia');

});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Backend/BookController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\BookRequest;
use App\Models\Book;
use App\Models\Category;
use App\Models\SubCategory;
use App\Models\TernaryCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::with('media')->latest()->orderBy('is_featured', 'desc')->get();
        return view('backend.book.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::isActive()->latest()->get();
        $subCategories = SubCategory::isActive()->latest()->get();
        $ternaryCategories = TernaryCategory::isActive()->latest()->get();
        return view('backend.book.create', compact('categories', 'subCategories', 'ternaryCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookRequest $request)
    {
        $request['customer_id'] = Auth::guard('customer')->user()->id ?? Auth::user()->id;
        $book = Book::create($request->all());
        foreach ($request->input('images', []) as $file) {
            $book->addMedia(storage_path('frontend/img/book/' . $file))->toMediaCollection('images');
        }
        return redirect()->route('book.index')->withMsg('Book Created Successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        $categories = Category::isActive()->latest()->get();
        $subCategories = SubCategory::isActive()->latest()->get();
        $ternaryCategories = TernaryCategory::isActive()->latest()->get();
        return view('backend.book.create', compact('book', 'categories', 'subCategories', 'ternaryCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BookRequest $request, Book $book)
    {
        $request['customer_id'] = Auth::guard('customer')->user()->id ?? Auth::user()->id;
        $book->update($request->all());
    if  (count($book->images) > 0) {
        foreach ($book->images as $media) {
            if (!in_array($media->file_name, $request->input('images', []))) {
                $media->delete();
            }
        }
    }
    $media = $book->images->pluck('file_name')->toArray();

    foreach ($request->input('images', []) as $file) {
        if (count($media) === 0 || !in_array($file, $media)) {
            $book->addMedia(storage_path('frontend/img/book/' . $file))->toMediaCollection('images');
        }
    }

        return redirect()->route('book.index')->withMsg('Book Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        if ($book->hasMedia('images')){
            $book->clearMediaCollection('images');
        }
        $book->delete();
        return redirect()->route('book.index')->withMsg('Book deleted sucessfully');
    }

    public function getTernaryCategories($id){
        $subCategories = TernaryCategory::where('sub_category_id', $id)->get();
        return response(json_encode($subCategories));
    }
    public function storeMedia(Request $request)
    {
    $path = storage_path('frontend/img/book');

    if (!file_exists($path)) {
        mkdir($path, 0777, true);
    }

    $file = $request->file('file');

    $name = uniqid() . '_' . trim($file->getClientOriginalName());

    $file->move($path, $name);

    return response()->json([
        'name'          => $name,
        'original_name' => $file->getClientOriginalName(),
    ]);
}
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Category::latest()->orderBy('order', 'asc')->get();
        return view('backend.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        Category::create($request->all());
        return redirect()->route('category.index')->withMsg('Category created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('backend.category.create', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update($request->all());
        return redirect()->route('category.index')->withMsg('Category updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return redirect()->route('category.index')->withMsg('Category deleted successfully.');
    }
}

app/Http/Controllers/Backend/ContactController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Contact;

class ContactController extends Controller
{
    public function index(){
        $contacts=Contact::latest()->get();
        return view('backend.contact', compact('contacts'));
    }
   public function destroy(Contact $contact){
        $contact->delete();
        return redirect()->route('contact.index')->withMsg('Message sucessfully deleted');
   }
}

app/Http/Controllers/Backend/SiteSettingController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\SiteSettingRequest;
use App\Models\SiteSetting;
use Illuminate\Http\Request;

class SiteSettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $edit = SiteSetting::first();
        return view('backend.settings.site', compact('edit'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SiteSettingRequest $request)
    {
        $edit = SiteSetting::first();
        if ($request->hasFile('logo')){
            $edit->clearMediaCollection();
            $edit->addMedia($request->file('logo'))->toMediaCollection();
        }
        if ($edit){
            $edit->update($request->all());
        }else{
           SiteSetting::create($request->all());
        }
        return redirect()->route('site-setting.index')->withMsg('Site Setting has been updated successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/SubCategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Backend\SubCategoryRequest;
use App\Models\Category;
use App\Models\SubCategory;

class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subCategories = SubCategory::latest()->get();
        return view('backend.sub_category.index', compact('subCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::isActive()->get();
        return view('backend.sub_category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubCategoryRequest $request)
    {
        SubCategory::create($request->all());
        return redirect()->route('sub_category.index')->withMsg('Sub-Category Created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(SubCategory $subCategory)
    {
        $categories = Category::isActive()->get();
        return view('backend.sub_category.create',compact('categories', 'subCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SubCategoryRequest $request, SubCategory $subCategory)
    {
        $subCategory->update($request->all());
        return redirect()->route('sub_category.index')->withMsg('Sub-Category Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(SubCategory $subCategory)
    {
        $subCategory->delete();
        return redirect()->route('sub_category.index')->withMsg('Sub-Category Deleted Successfully.');
    }
}

resources/views/backend/layouts/footer.blade.php
<?php //
//$config = App\Backend\SiteConfiguration::first();
//?>
<footer class="main-footer d-flex p-2 px-3 bg-white border-top">
  <ul class="nav">
    <li class="nav-item">
    <a class="nav-link" href="{{ url('admin') }}">Dashboard</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="#">Group</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Category</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">News</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="#">Tag</a>
    </li>
  </ul>
  <span class="copyright ml-auto my-auto mr-2">Copyright © <script>document.write(new Date().getFullYear())</script> Portfolio
    <a href="{{url('/')}}" rel="nofollow">
{{--        {{$config->name_en ?? ''}}--}}
    </a>
  </span>
</footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{{-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script> --}}
<script src="https://unpkg.com/shards-ui@latest/dist/js/shards.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Sharrre/2.0.1/jquery.sharrre.min.js"></script>
<script src="{{asset('backend/scripts/extras.1.1.0.min.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

@yield('js')
<script type="text/javascript">
  $(function($) {
    let url = '{{url()->current()}}';
    $('.nav-item a').removeClass('active');
    $('.nav-item a').each(function() {
      if (this.href === url) {
        $(this).addClass('active');
        // if($(this).parents('.has-child').length > 0){
          $(this).parents('.collapse').addClass('show');
        // }
      }
    });
  });
  $(document).ready(function() {
    setTimeout(function() {
      $('.alert .close').click()
    }, 3000);
    $('#aboutus-table').DataTable();
  });
</script>
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>--}}
<script src="{{asset('backend/scripts/app/app-blog-overview.1.1.0.js')}}"></script>

resources/views/backend/layouts/sidebar.blade.php
<!-- Main Sidebar -->
<?php //
//  $maintenance = Cache::get('maintenance') ?? 'off';
//?>
<aside class="main-sidebar col-12 col-md-3 col-lg-2 px-0">
    <div class="main-navbar">
        <nav class="navbar align-items-stretch navbar-light bg-white flex-md-nowrap border-bottom p-0">
            <a class="navbar-brand w-100 mr-0" href="{{route('dashboard')}}" style="line-height: 25px;">
                <div class="d-table m-auto">
                    {{--          <img id="main-logo" class="d-inline-block align-top mr-1" style="max-width: 25px;" src="{{asset('images/shards-dashboards-logo.svg')}}" alt="Shards Dashboard">--}}
                    <span class="d-none d-md-inline ml-1">{{config('app.name')}} Dashboard</span>
                </div>
            </a>
            <a class="toggle-sidebar d-sm-inline d-md-none d-lg-none">
                <i class="material-icons">&#xE5C4;</i>
            </a>
        </nav>
    </div>
    <form action="#" class="main-sidebar__search w-100 border-right d-sm-flex d-md-none d-lg-none">
        <div class="input-group input-group-seamless ml-3">
            <div class="input-group-prepend">
                <div class="input-group-text">
                    <i class="fas fa-search"></i>
                </div>
            </div>
            <input class="navbar-search form-control" type="text" placeholder="Search for something..."
                   aria-label="Search"></div>
    </form>

    {{--  <div class="row p-3">--}}
    {{--    <label id="labelMaintenance" for="maintenance" class="mx-auto">Maintenance Mode</label>--}}
    {{--    <div class="custom-control custom-switch ml-auto">--}}
    {{--        <input type="checkbox" class="custom-control-input" id="maintenance" onclick="$('#maintenanceForm').submit()" {{ $maintenance=='on'?'Checked':'' }}>--}}
    {{--        <label class="custom-control-label" onclick="$('#labelMaintenance').click()"></label>--}}
    {{--    </div>--}}
    {{--</div>--}}
    {{--<form id="maintenanceForm" action="#" method="post">--}}
    {{--    @csrf--}}
    {{--</form>--}}
    <div class="nav-wrapper accordion" id="accordionExample">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="{{route('dashboard')}}">
                    <i class="material-icons">edit</i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link " href="components-blog-posts.html">
                <i class="material-icons">vertical_split</i>
                <span>Blog Posts</span>
              </a>
            </li> -->

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="headingOne">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapseOne"
                         aria-expanded="false" aria-controls="collapseOne">
                        <i class="material-icons">note_add</i>
                        <span> Settings</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('site-setting.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Site Settings</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="headingTwo">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapseTwo"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Category Setup</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('category.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Category List</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('sub_category.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Sub-Category List</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('ternary_category.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Ternary Category List</span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="nav-item has-child">
                <div class="card-header p-0 m-0" id="heading9">
                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"
                         data-target="#collapse9"
                         aria-expanded="false" aria-controls="collapseTwo">
                        <i class="material-icons">note_add</i>
                        <span>Manage Book Section</span>
                        <i class="fa fa-plus ml-auto"></i>
                    </div>
                </div>
                <div id="collapse9" class="collapse" aria-labelledby="heading9" data-parent="#accordionExample">
                    <div class="card-body p-0">
                        <a class="nav-link p-2 pl-5" href="{{route('book.create')}}">
                            <i class="material-icons">note_add</i>
                            <span>Add Book</span>
                        </a>
                        <a class="nav-link p-2 pl-5" href="{{route('book.index')}}">
                            <i class="material-icons">note_add</i>
                            <span>Book List</span>
                        </a>
                    </div>
                </div>
            </div>

{{--            <div class="nav-item has-child">--}}
{{--                <div class="card-header p-0 m-0" id="heading6">--}}
{{--                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"--}}
{{--                         data-target="#collapse6"--}}
{{--                         aria-expanded="false" aria-controls="collapseTwo">--}}
{{--                        <i class="material-icons">note_add</i>--}}
{{--                        <span>Gallery Setup</span>--}}
{{--                        <i class="fa fa-plus ml-auto"></i>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div id="collapse6" class="collapse" aria-labelledby="heading6" data-parent="#accordionExample">--}}
{{--                    <div class="card-body p-0">--}}
{{--                        <a class="nav-link p-2 pl-5" href="{{route('gallery.create')}}">--}}
{{--                            <i class="material-icons">note_add</i>--}}
{{--                            <span>Add Gallery</span>--}}
{{--                        </a>--}}
{{--                        <a class="nav-link p-2 pl-5" href="{{route('gallery.index')}}">--}}
{{--                            <i class="material-icons">note_add</i>--}}
{{--                            <span>Gallery List</span>--}}
{{--                        </a>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--            <div class="nav-item has-child">--}}
{{--                <div class="card-header p-0 m-0" id="heading5">--}}
{{--                    <div class="nav-link collapsed d-flex align-items-center" data-toggle="collapse"--}}
{{--                         data-target="#collapse5"--}}
{{--                         aria-expanded="false" aria-controls="collapseTwo">--}}
{{--                        <i class="material-icons">note_add</i>--}}
{{--                        <span>News Setup</span>--}}
{{--                        <i class="fa fa-plus ml-auto"></i>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div id="collapse5" class="collapse" aria-labelledby="heading5" data-parent="#accordionExample">--}}
{{--                    <div class="card-body p-0">--}}
{{--                        <a class="nav-link p-2 pl-5" href="{{route('news.create')}}">--}}
{{--                            <i class="material-icons">note_add</i>--}}
{{--                            <span>Add News</span>--}}
{{--                        </a>--}}
{{--                        <a class="nav-link p-2 pl-5" href="{{route('news.index')}}">--}}
{{--                            <i class="material-icons">note_add</i>--}}
{{--                            <span>News List</span>--}}
{{--                        </a>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

           <li class="nav-item">
               <a class="nav-link " href="{{route('contact.index')}}">
                  <i class="material-icons">note_add</i>
                   <span>Contacts </span>
              </a>
         </li>

        </ul>
    </div>
</aside>